---
- name: is this thing on?
  hosts: all
  tasks:
    - command: uname -a
      register: uname
    - debug: var=uname
  tags:
    - always

- name: build chat server
  hosts: chatsrv
  roles:
    - role: nginx
      tags:
        - nginx
    - role: simple-chat
      tags:
        - simple-chat
