---
- name: install deps
  apt:
    name: "{{ item }}"
  with_items:
    - rsync

- name: create simple-chat user
  user:
    name: simple-chat
    home: "{{ simplechat.home }}"
    system: yes

- name: create simple-chat install dir
  file:
    path: "{{ simplechat.install.dest | regex_replace('(.*\\/).*', '\\1') }}"
    state: directory
    owner: simple-chat
    group: simple-chat

- name: extract simple-chat
  unarchive:
    src: "{{ simplechat.install.source }}"
    dest: "{{ simplechat.install.dest }}"
    copy: no
  notify:
    - restart simple-chat

- name: fix perms simple-chat install dir
  file:
    path: "{{ simplechat.install.dest | regex_replace('(.*\\/).*', '\\1') }}"
    state: directory
    owner: simple-chat
    group: simple-chat
    recurse: true

- name: fix perms simple-chat binary
  file:
    path: "{{ simplechat.install.dest }}/{{ simplechat.install.binary }}"
    owner: simple-chat
    group: simple-chat
    mode: 0755

- name: install simple-chat upstart
  template:
    src: etc/init/simple-chat.conf
    dest: /etc/init/simple-chat.conf
  notify:
    - restart simple-chat

- meta: flush_handlers

- name: start simple-chat service
  service:
    name: simple-chat
    enabled: yes
    state: started
